@file:Suppress("unused")

package ms.mattschlenkrich.paydaycalculator.common

const val DB_NAME = "bills2.db"
const val PAY_DB_NAME = "pay.db"
const val DB_VERSION = 1
const val PAY_DB_VERSION = 1
const val BILLS_DATABASE = "BillsDatabase"

const val SQLITE_DATE = "yyyy-LL-dd"
const val SQLITE_TIME = "yyyy-LL-dd HH:mm:ss"
const val DATE_CHECK = "yyyy-MM-dd"
const val DATE_CHECK_WITH_YEAR = "?"
const val DISPLAY_DATE = "EEE dd LLL"
const val DISPLAY_DATE_WITH_YEAR = "EEE dd LLL /yy"

const val FRAG_ACCOUNT_ADD = "AccountAdd"
const val FRAG_ACCOUNTS = "Accounts"
const val FRAG_ACCOUNT_TYPE_ADD = "AccountTypeAdd"
const val FRAG_ACCOUNT_TYPES = "AccountTypes"
const val FRAG_ACCOUNT_TYPE_UPDATE = "AccountTypeUpdate"
const val FRAG_ACCOUNT_UPDATE = "AccountUpdate"
const val FRAG_BUDGET_RULES = "BudgetRules"
const val FRAGMENT_CALC = "CalcFragment"
const val FRAG_DAYS_OF_WEEK = "DaysOfWeek"
const val FRAG_BUDGET_RULE_ADD = "BudgetRuleAdd"
const val FRAG_BUDGET_RULE_UPDATE = "BudgetRuleUpdate"
const val FRAG_TRANSACTIONS = "Transactions"
const val FRAG_TRANS_ADD = "TransactionAdd"
const val FRAG_TRANS_UPDATE = "TransactionUpdate"
const val FRAG_TRANS_PERFORM = "TransactionPerform"
const val FRAG_BUDGET_VIEW = "BudgetView"
const val FRAG_BUDGET_ITEM_ADD = "BudgetItemAdd"
const val FRAG_BUDGET_ITEM_UPDATE = "BudgetItemUpdate"
const val FRAG_BUDGET_LIST = "BudgetList"
const val FRAG_TRANSACTION_ANALYSIS = "TransactionAnalysis"
const val FRAG_TRANSACTION_SPLIT = "TransactionSplit"

const val ADAPTER_BUDGET_RULE = "BudgetRuleAdapter"
const val ADAPTER_BUDGET_LIST = "BudgetListMonthlyAdapter"
const val ADAPTER_ACCOUNT = "AccountAdapter"
const val ADAPTER_ACCOUNT_TYPE = "AccountTypeAdapter"
const val ADAPTER_TRANSACTION = "TransactionAdapter"
const val ADAPTER_BUDGET_VIEW = "BudgetViewAdapter"
const val ADAPTER_PENDING = "TransactionPendingAdapter"
const val ADAPTER_TRANSACTION_ANALYSIS = "TransactionAnalysisAdapter"

const val TABLE_ACCOUNT_TYPES = "accountTypes"
const val TYPE_ID = "typeId"
const val ACCOUNT_TYPE = "accountType"
const val KEEP_BALANCE = "keepTotals"
const val IS_ASSET = "isAsset"
const val TALLY_OWING = "tallyOwing"
const val KEEP_MILEAGE = "keepMileage"
const val ALLOW_PENDING = "allowPending"
const val ACCT_DISPLAY_AS_ASSET = "displayAsAsset"
const val ACCT_IS_DELETED = "acctIsDeleted"
const val ACCT_UPDATE_TIME = "acctUpdateTime"

const val TABLE_ACCOUNTS = "accounts"
const val ACCOUNT_ID = "accountId"
const val ACCOUNT_NAME = "accountName"
const val ACCOUNT_NUMBER = "accountNumber"
const val ACCOUNT_TYPE_ID = "accountTypeId"
const val ACCOUNT_BUDGETED_AMOUNT = "accBudgetedAmount"
const val ACCOUNT_BALANCE = "accountBalance"
const val ACCOUNT_OWING = "accountOwing"
const val ACCOUNT_CREDIT_LIMIT = "accountCreditLimit"
const val ACCOUNT_IS_DELETED = "accIsDeleted"
const val ACCOUNT_UPDATE_TIME = "accUpdateTime"
const val VIEW_ACCOUNT_WITH_TYPE = "accountWithType"

const val TABLE_BUDGET_RULES = "budgetRules"
const val RULE_ID = "ruleId"
const val BUDGET_RULE_NAME = "budgetRuleName"
const val BUD_TO_ACCOUNT_ID = "budToAccountId"
const val BUD_FROM_ACCOUNT_ID = "budFromAccountId"
const val BUDGET_AMOUNT = "budgetAmount"
const val BUD_FIXED_AMOUNT = "budFixedAmount"
const val BUD_IS_PAY_DAY = "budIsPayDay"
const val BUD_IS_AUTO_PAY = "budIsAutoPay"
const val BUD_START_DATE = "budStartDate"
const val BUD_END_DATE = "budEndDate"
const val BUD_DAY_OF_WEEK_ID = "budDayOfWeekId"
const val BUD_FREQUENCY_TYPE_ID = "budFrequencyTypeId"
const val BUD_FREQUENCY_COUNT = "budFrequencyCount"
const val BUD_LEAD_DAYS = "budLeadDays"
const val BUD_IS_DELETED = "budIsDeleted"
const val BUD_UPDATE_TIME = "budUpdateTime"

const val TABLE_BUDGET_ITEMS = "budgetItems"
const val BI_BUDGET_RULE_ID = "biRuleId"
const val BI_PROJECTED_DATE = "biProjectedDate"
const val BI_TO_ACCOUNT_ID = "biToAccountId"
const val BI_FROM_ACCOUNT_ID = "biFromAccountId"
const val BI_ACTUAL_DATE = "biActualDate"
const val BI_PAY_DAY = "biPayDay"
const val BI_BUDGET_NAME = "biBudgetName"
const val BI_IS_PAY_DAY_ITEM = "biIsPayDayItem"
const val BI_PROJECTED_AMOUNT = "biProjectedAmount"
const val BI_IS_AUTOMATIC = "biIsAutomatic"
const val BI_IS_FIXED = "biIsFixed"
const val BI_IS_MANUALLY_ENTERED = "biManuallyEntered"
const val BI_LOCKED = "biLocked"
const val BI_IS_COMPLETED = "biIsCompleted"
const val BI_IS_CANCELLED = "biIsCancelled"
const val BI_IS_DELETED = "biIsDeleted"
const val BI_UPDATE_TIME = "biUpdateTime"

const val TABLE_TRANSACTION = "transactions"
const val TRANSACTION_ID = "transId"
const val TRANSACTION_DATE = "transDate"
const val TRANS_BUDGET_RULE_ID = "transRuleId"
const val TRANSACTION_TO_ACCOUNT_ID = "transToAccountId"
const val TRANSACTION_TO_ACCOUNT_PENDING = "transToAccountPending"
const val TRANSACTION_FROM_ACCOUNT_ID = "transFromAccountId"
const val TRANSACTION_FROM_ACCOUNT_PENDING = "transFromAccountPending"
const val TRANSACTION_NAME = "transName"
const val TRANSACTION_NOTE = "transNote"
const val TRANSACTION_AMOUNT = "transAmount"
const val TRANS_IS_PENDING = "transIsPending"
const val TRANS_IS_DELETED = "transIsDeleted"
const val TRANS_UPDATE_TIME = "transUpdateTime"

const val TABLE_EMPLOYERS = "employers"
const val EMPLOYER_ID = "employerId"
const val EMPLOYER_NAME = "employerName"
const val EMPLOYER_IS_DELETED = "employerIsDeleted"
const val EMPLOYER_UPDATE_TIME = "employerUpdateTime"

const val TABLE_EMPLOYER_TAX_RULES = "employerTaxRules"
const val EMPLOYER_TAX_RULES_EMPLOYER_ID = "etrEmployerId"
const val EMPLOYER_TAX_RULES_TAX_TYPE = "etrTaxType"
const val EMPLOYER_TAX_RULES_INCLUDE = "etrInclude"
const val EMPLOYER_TAX_RULES_IS_DELETED = "etrIsDeleted"
const val EMPLOYER_TAX_RULES_UPDATE_TIME = "etrUpdateTime"


const val TABLE_WORK_PAY_PERIODS = "workPayPeriods"
const val PAY_PERIOD_CUTOFF_DATE = "ppCutoffDate"
const val PAY_PERIOD_EMPLOYER_ID = "ppEmployerId"
const val PAY_PERIOD_UPDATE_TIME = "ppUpdateTime"
const val PAY_PERIOD_IS_DELETED = "ppIsDeleted"

const val TABLE_WORK_DATES = "workDates"
const val WORK_DATES_EMPLOYER_ID = "wdEmployerId"
const val WORK_DATES_CUTOFF_DATE = "wdCutoffDate"
const val WORK_DATES_DATE = "wdDate"
const val WORK_DATES_REG_HOURS = "wdRegHours"
const val WORK_DATES_OT_HOURS = "wdOtHours"
const val WORK_DATES_DBL_OT_HOURS = "wdDblOtHours"
const val WORK_DATES_STAT_HOURS = "wdStatHours"
const val WORK_DATES_IS_DELETED = "wdIsDeleted"
const val WORK_DATES_UPDATE_TIME = "wdUpdateTime"

const val TABLE_WORK_EXTRAS_DEFINITIONS = "workExtrasDefinitions"
const val WORK_EXTRA_ID = "workExtraId"
const val WORK_EXTRA_EMPLOYER_ID = "weEmployerId"
const val WORK_EXTRA_NAME = "weName"
const val WORK_EXTRA_VALUE = "weValue"
const val WORK_EXTRA_FREQUENCY = "weFrequency"
const val WORK_EXTRA_IS_CREDIT = "weIsCredit"
const val WORK_EXTRA_IS_DEFAULT = "weIsDefault"
const val WORK_EXTRA_EFFECTIVE_DATE = "weEffectiveDate"
const val WORK_EXTRA_IS_DELETED = "wedIsDeleted"
const val WORK_EXTRA_UPDATE_TIME = "weUpdateTime"

const val TABLE_WORK_EXTRA_FREQUENCIES = "workExtraFrequencies"
const val WORK_EXTRA_FREQUENCY_NAME = "workExtraFrequencyName"

const val TABLE_WORK_DATES_EXTRAS = "workDatesExtras"
const val WORK_DATES_EXTRAS_EMPLOYER_ID = "wdeEmployerId"
const val WORK_DATES_EXTRAS_DATE = "wdeDate"
const val WORK_DATES_EXTRAS_NAME = "wdeName"
const val WORK_DATES_EXTRA_ID = "wdeId"
const val WORK_DATES_EXTRAS_IS_DELETED = "wdeIsDeleted"
const val WORK_DATES_EXTRAS_UPDATE_TIME = "wdeUpdateTime"

const val WORK_EXTRA_FREQUENCY_HOURLY = "hourly"
const val WORK_EXTRA_FREQUENCY_DAILY = "daily"
const val WORK_EXTRA_FREQUENCY_PER_PAY = "per pay"

const val TABLE_WORK_TAX_TYPES = "workTaxTypes"
const val WORK_TAX_TYPE = "workTaxType"
const val WORK_TAX_TYPE_IS_DELETED = "wttIsDeleted"
const val WORK_TAX_TYPE_UPDATE_TIME = "wttUpdateTime"

const val TABLE_WORK_TAX_RULES = "workTaxRules"
const val WORK_TAX_RULE_ID = "workTaxRuleId"
const val WORK_TAX_RULE_TYPE = "workTaxRuleType"
const val WORK_TAX_RULE_PERCENT = "wtPercent"
const val WORK_TAX_RULE_HAS_EXEMPTION = "wtHasExemption"
const val WORK_TAX_RULE_EXEMPTION_AMOuNT = "wtExemptionAmount"
const val WORK_TAX_RULE_HAS_BRACKET = "wtHasBracket"
const val WORK_TAX_RULE_BRACKET_AMOuNT = "wtBracketAmount"
const val WORK_TAX_RULE_EFFECTIVE_DATE = "wtEffectiveDate"
const val WORK_TAX_RULE_IS_DELETED = "wtIsDeleted"
const val WORK_TAX_RULE_UPDATE_TIME = "wtUpdateTime"

const val TABLE_WORK_PAY_PERIOD_EXTRAS = "workPayPeriodExtras"
const val WORK_PAY_PERIOD_EXTRA_EMPLOYER_ID = "ppeEmployerId"
const val WORK_PAY_PERIOD_EXTRA_CUTOFF_DATE = "ppeCutoffDate"
const val WORK_PAY_PERIOD_EXTRA_ID = "ppeExtraId"
const val WORK_PAY_PERIOD_EXTRA_NAME = "ppeName"
const val WORK_PAY_PERIOD_EXTRA_VALUE = "ppeValue"
const val WORK_PAY_PERIOD_EXTRA_IS_DELETED = "ppeIsDeleted"
const val WORK_PAY_PERIOD_EXTRA_UPDATE_TIME = "ppeUpdateTime"

const val TABLE_WORK_PAY_PERIOD_TAX = "workPayPeriodTax"
const val PAY_PERIOD_TAX_CUTOFF_DATE = "wppCutoffDate"
const val PAY_PERIOD_TAX_EMPLOYER_ID = "wppEmployerId"
const val PAY_PERIOD_TAX_TYPE = "wppTaxType"
const val PAY_PERIOD_TAX_IS_DELETED = "wppIsDeleted"
const val PAY_PERIOD_TAX_UPDATE_TIME = "wppUpdateTime"

const val REQUEST_TO_ACCOUNT = "toAccount"
const val REQUEST_FROM_ACCOUNT = "fromAccount"

const val ANSWER_OK = "Ok"

const val DAY_MONDAY = "Monday"
const val DAY_TUESDAY = "Tuesday"
const val DAY_WEDNESDAY = "Wednesday"
const val DAY_THURSDAY = "Thursday"
const val DAY_FRIDAY = "Friday"
const val DAY_SATURDAY = "Saturday"
const val DAY_SUNDAY = "Sunday"
const val DAY_WEEK_DAY = "Week Day"
const val DAY_ANY_DAY = "Any Day"
const val DAY_PAY_DAY = "Pay Day"

const val INTERVAL_WEEKLY = "Weekly"
const val INTERVAL_MONTHLY = "Monthly"
const val INTERVAL_YEARLY = "Yearly"
const val INTERVAL_ON_PAY_DAY = "On Payday"
const val INTERVAL_SPECIAL = "Special"
const val INTERVAL_ONE_TIME = "One Time"

const val FREQ_MONTHLY = 0
const val FREQ_WEEKLY = 1
const val FREQ_YEARLY = 2
const val FREQ_PAYDAY = 3
const val FREQ_MANUALLY = 4
const val FREQ_SPECIAL = 5

const val BALANCE = "Balance"
const val OWING = "Owing"
const val BUDGETED = "Budgeted"

const val WAIT_250 = 250L
const val WAIT_500 = 500L
const val WAIT_1000 = 1000L

